### ISSUE TITLE
linux/bfd.c unable to compile with binutils 2.29

### ISSUE THREAD

**Issue by Barro** [google/honggfuzz#162]
I noticed that I'm unable to compile honggfuzz on Debian testing due to following issue:

```
cc -c -O3 -D_GNU_SOURCE -Wall -Werror -Wframe-larger-than=131072 -Wno-format-truncation -std=c11 -I/usr/local/include -I/usr/include -Wextra -Wno-override-init -funroll-loops -D_FILE_OFFSET_BITS=64 -D_HF_ARCH_LINUX -o linux/bfd.o linux/bfd.c
linux/bfd.c: In function ‘arch_bfdDisasm’:
linux/bfd.c:164:51: error: incompatible type for argument 1 of ‘disassembler’
     disassembler_ftype disassemble = disassembler(bfdh);
                                                   ^~~~
In file included from linux/bfd.c:28:0:
/usr/include/dis-asm.h:276:27: note: expected ‘enum bfd_architecture’ but argument is of type ‘bfd * {aka struct bfd *}’
 extern disassembler_ftype disassembler (enum bfd_architecture arc,
                           ^~~~~~~~~~~~
linux/bfd.c:164:38: error: too few arguments to function ‘disassembler’
     disassembler_ftype disassemble = disassembler(bfdh);
                                      ^~~~~~~~~~~~
In file included from linux/bfd.c:28:0:
/usr/include/dis-asm.h:276:27: note: declared here
 extern disassembler_ftype disassembler (enum bfd_architecture arc,
                           ^~~~~~~~~~~~
Makefile:247: recipe for target 'linux/bfd.o' failed
make: *** [linux/bfd.o] Error 1
```

It looks like binutils have changed the interface of disassembler function between 2.28 and 2.29 from:

```
extern disassembler_ftype disassembler (bfd *);
```

to:

```
extern disassembler_ftype disassembler (enum bfd_architecture arc,
                                        bfd_boolean big, unsigned long mach,
                                        bfd *abfd);
```

**Comment by robertswiecki** [comment]
Interesting, lemme try to update the code

**Comment by robertswiecki** [comment]
Some ugly fix in https://github.com/google/honggfuzz/commit/fe2934bd59e7a1dbe58dafcd71bb8383505de092

Needs some more testing with >= 2.29

**Comment by robertswiecki** [comment]
Seems it works well.
