### ISSUE TITLE
Fails to build with glibc >2.38

### ISSUE THREAD

**Issue by PaulGrandperrin** [google/honggfuzz#518]
With glibc 2.37 everything builds and works fine.

With glibc 2.38 and later (also tried 2.39 and 2.40), I get those errors:
```
gcc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -fPIC -fno-stack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0   -o libhfuzz/memorycmp.o libhfuzz/memorycmp.c
In file included from /nix/store/jmmjgq4v8anmnz6hfzd447jb77vi6xii-glibc-2.38-77-dev/include/features.h:503,
                 from /nix/store/jmmjgq4v8anmnz6hfzd447jb77vi6xii-glibc-2.38-77-dev/include/ctype.h:25,
                 from libhfuzz/memorycmp.c:1:
/nix/store/jmmjgq4v8anmnz6hfzd447jb77vi6xii-glibc-2.38-77-dev/include/bits/string_fortified.h:77:1: error: ‘strcpy’ defined both normally and as ‘alias’ attribute
   77 | __NTH (strcpy (char *__restrict __dest, const char *__restrict __src))
      | ^~~~~
/nix/store/jmmjgq4v8anmnz6hfzd447jb77vi6xii-glibc-2.38-77-dev/include/bits/string_fortified.h:128:1: error: ‘strcat’ defined both normally and as ‘alias’ attribute
  128 | __NTH (strcat (char *__restrict __dest, const char *__restrict __src))
      | ^~~~~
/nix/store/jmmjgq4v8anmnz6hfzd447jb77vi6xii-glibc-2.38-77-dev/include/bits/string_fortified.h:150:1: error: ‘strlcpy’ defined both normally and as ‘alias’ attribute
  150 | __NTH (strlcpy (char *__restrict __dest, const char *__restrict __src,
      | ^~~~~
/nix/store/jmmjgq4v8anmnz6hfzd447jb77vi6xii-glibc-2.38-77-dev/include/bits/string_fortified.h:167:1: error: ‘strlcat’ defined both normally and as ‘alias’ attribute
  167 | __NTH (strlcat (char *__restrict __dest, const char *__restrict __src,
      | ^~~~~
make: *** [Makefile:307: libhfuzz/memorycmp.o] Error 1
```

**Comment by robertswiecki** [comment]
Hi, could you

```
gcc -E -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -D_FILE_OFFSET_BITS=64 -finline-limit=4000 -D_HF_ARCH_LINUX -fPIC -fno-stack-protector -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=0   -o /tmp/out.txt libhfuzz/memorycmp.c
```

and see in ```/tmp/out.txt``` why ```bits/string_fortified.h``` gets included at all

**Comment by PaulGrandperrin** [comment]
Hi!
Here's `/tmp/out.txt` : https://gist.github.com/PaulGrandperrin/8fbcdfeb10274394987148b8ffe3e36b

If you already know a little bit nix/nixos, I could provide you with a reproducible build environment for this if you wish

**Comment by robertswiecki** [comment]
I `think` Nix enables fortify by default in gcc?, and it must be disabled for honggfuzz. Here's the package for honggfuzz, I guess it specifies this https://github.com/NixOS/nixpkgs/blob/c15c74ff6abf5f90eebba0062614839a20564cd0/pkgs/tools/security/honggfuzz/default.nix#L42

**Comment by PaulGrandperrin** [comment]
Oh good catch, I really should have found out that myself... I never checked out nixpkgs's version of honggfuzz!

Thanks for the help
