### ISSUE TITLE
can't compile in freebsd12, clang version 9.0.1

### ISSUE THREAD

**Issue by leeeddin** [google/honggfuzz#363]
root@freebsd:~/honggfuzz-master # cc -v
clang version 9.0.1
Target: i386-portbld-freebsd12.1
Thread model: posix
InstalledDir: /usr/bin

root@freebsd:~/honggfuzz-master # gmake
gmake: Warning: File 'Makefile' has modification time 2245596 s in the future
cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -Wno-initializer-overrides -Wno-unknown-warning-option -Wno-unknown-pragmas -Wno-initializer-overrides -Wno-unknown-warning-option -Wno-gnu-empty-initializer -Wno-format-pedantic -Wno-gnu-statement-expression -mllvm -inline-threshold=2000 -D_HF_ARCH_POSIX -fblocks -o cmdline.o cmdline.c
cc -c -O3 -mtune=native -funroll-loops -std=c11 -I/usr/local/include -D_GNU_SOURCE -Wall -Wextra -Werror -Wno-format-truncation -Wno-override-init -I. -Wno-initializer-overrides -Wno-unknown-warning-option -Wno-unknown-pragmas -Wno-initializer-overrides -Wno-unknown-warning-option -Wno-gnu-empty-initializer -Wno-format-pedantic -Wno-gnu-statement-expression -mllvm -inline-threshold=2000 -D_HF_ARCH_POSIX -fblocks -o display.o display.c
display.c:283:13: error: misaligned atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
            ATOMIC_GET(hfuzz->feedback.hwCnts.cpuInstrCnt));
            ^
./libhfcommon/util.h:111:27: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x)     __atomic_load_n(&(x), __ATOMIC_RELAXED)
                          ^
display.c:287:13: error: misaligned atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
            ATOMIC_GET(hfuzz->feedback.hwCnts.cpuBranchCnt));
            ^
./libhfcommon/util.h:111:27: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x)     __atomic_load_n(&(x), __ATOMIC_RELAXED)
                          ^
display.c:291:13: error: misaligned atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
            ATOMIC_GET(hfuzz->feedback.hwCnts.bbCnt));
            ^
./libhfcommon/util.h:111:27: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x)     __atomic_load_n(&(x), __ATOMIC_RELAXED)
                          ^
display.c:295:13: error: misaligned atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
            ATOMIC_GET(hfuzz->feedback.hwCnts.bbCnt));
            ^
./libhfcommon/util.h:111:27: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x)     __atomic_load_n(&(x), __ATOMIC_RELAXED)
                          ^
display.c:298:32: error: misaligned atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
        uint64_t softCntPc   = ATOMIC_GET(hfuzz->feedback.hwCnts.softCntPc);
                               ^
./libhfcommon/util.h:111:27: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x)     __atomic_load_n(&(x), __ATOMIC_RELAXED)
                          ^
display.c:299:32: error: misaligned atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
        uint64_t softCntEdge = ATOMIC_GET(hfuzz->feedback.hwCnts.softCntEdge);
                               ^
./libhfcommon/util.h:111:27: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x)     __atomic_load_n(&(x), __ATOMIC_RELAXED)
                          ^
display.c:300:32: error: misaligned atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
        uint64_t softCntCmp  = ATOMIC_GET(hfuzz->feedback.hwCnts.softCntCmp);
                               ^
./libhfcommon/util.h:111:27: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x)     __atomic_load_n(&(x), __ATOMIC_RELAXED)
                          ^
display.c:301:32: error: misaligned atomic operation may incur significant performance penalty [-Werror,-Watomic-alignment]
        uint64_t guardNb     = ATOMIC_GET(hfuzz->feedback.covFeedbackMap->guardNb);
                               ^
./libhfcommon/util.h:111:27: note: expanded from macro 'ATOMIC_GET'
#define ATOMIC_GET(x)     __atomic_load_n(&(x), __ATOMIC_RELAXED)
                          ^
8 errors generated.
gmake: *** [Makefile:259: display.o] Error 1

**Comment by vanhauser-thc** [comment]
removing -Werror from the Makefiles will allow you to continue compiling

**Comment by leeeddin** [comment]
> removing -Werror from the Makefiles will allow you to continue compiling

it worked, but have another error:

ar rcs libhfcommon/libhfcommon.a libhfcommon/files.o libhfcommon/log.o libhfcommon/ns.o libhfcommon/util.o
cc -o honggfuzz cmdline.o display.o fuzz.o honggfuzz.o input.o mangle.o report.o sanitizers.o socketfuzzer.o subproc.o posix/arch.o libhfcommon/libhfcommon.a -pthread -lm -L/usr/local/lib -lm -lrt -Wl,-Bstatic -lBlocksRuntime -Wl,-Bdynamic
ld: error: undefined symbol: __atomic_load_8
>>> referenced by display.c
>>>               display.o:(display_display)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by display.c
>>>               display.o:(display_display)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by display.c
>>>               display.o:(display_display)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by display.c
>>>               display.o:(display_display)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by display.c
>>>               display.o:(display_display)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by display.c
>>>               display.o:(display_display)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by display.c
>>>               display.o:(display_display)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by display.c
>>>               display.o:(display_display)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_store_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_store_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_store_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_store_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_store_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_load_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: undefined symbol: __atomic_store_8
>>> referenced by fuzz.c
>>>               fuzz.o:(fuzz_threadNew)

ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
cc: error: linker command failed with exit code 1 (use -v to see invocation)
gmake: *** [Makefile:275: honggfuzz] Error 1
root@freebsd:~/honggfuzz-master

**Comment by robertswiecki** [comment]
I will take a look soon at this, but can you quickly add -latomic to LDFLAGS in the Makefile and try with it?

**Comment by leeeddin** [comment]
LDFLAG ?= -L/usr/local/lib/gcc9 -latomic
worked
