### ISSUE TITLE
Mac OS X 10.13.2 compilation issues with r1.3

### ISSUE THREAD

**Issue by iZsh** [google/honggfuzz#182]
Hello,
I'm trying to compile honggfuzz 1.3, running a fresh install of OS X 10.13.2
(I pretty much had the same issue with the master)

% make
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -c -O3 -D_GNU_SOURCE -Wall -Werror -Wframe-larger-than=131072 -Wno-format-truncation -Wno-unknown-warning -I. -arch x86_64 -std=c99 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk -x objective-c -pedantic -fblocks -Wimplicit -Wunused -Wcomment -Wchar-subscripts -Wuninitialized -Wreturn-type -Wpointer-arith -Wno-gnu-case-range -Wno-gnu-designator -Wno-deprecated-declarations -Wno-unknown-pragmas -Wno-attributes -D_HF_ARCH_DARWIN -o cmdline.o cmdline.c
error: unknown warning option '-Wno-format-truncation' [-Werror,-Wunknown-warning-option]
error: unknown warning option '-Wno-unknown-warning'; did you mean '-Wno-unknown-argument'? [-Werror,-Wunknown-warning-option]
make: *** [cmdline.o] Error 1

% /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc --version
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.3.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

I tried to remove "-Werror" from the Makefile to see how far i can compile. It fails later on:

libhfuzz/instrument.c:139:26: error: only weak aliases are supported on darwin
    __attribute__((weak, alias("__sanitizer_cov_trace_cmp1")));
                         ^
libhfuzz/instrument.c:141:26: error: only weak aliases are supported on darwin
    __attribute__((weak, alias("__sanitizer_cov_trace_cmp2")));
                         ^
libhfuzz/instrument.c:143:26: error: only weak aliases are supported on darwin
    __attribute__((weak, alias("__sanitizer_cov_trace_cmp4")));
                         ^
libhfuzz/instrument.c:145:26: error: only weak aliases are supported on darwin
    __attribute__((weak, alias("__sanitizer_cov_trace_cmp8")));
                         ^
2 warnings and 4 errors generated.
make: *** [libhfuzz/instrument.o] Error 1

**Comment by robertswiecki** [comment]
Hi, can you try changing

void __sanitizer_cov_trace_const_cmp1(uint8_t Arg1, uint8_t Arg2)
    __attribute__((HF_DARWIN_WEAK alias("__sanitizer_cov_trace_cmp1")));


to

void __sanitizer_cov_trace_const_cmp1(uint8_t Arg1, uint8_t Arg2)
    __attribute__((weakref("__sanitizer_cov_trace_cmp1")));

for each cmpX?

**Comment by robertswiecki** [comment]
or, please try with https://github.com/google/honggfuzz/commit/c4b067be83c0406f94412d49344b627d095e3dac

**Comment by robertswiecki** [comment]
Hm.. wrong change - here: https://github.com/google/honggfuzz/commit/0524d0b65b221c647ac0e9eaa6a1110c9fa6672d

**Comment by robertswiecki** [comment]
The reason the Makefile doesn't add some relevant flags is that this command

```shell
cc -v 2>&1 | grep -oE '((gcc|clang) version|LLVM version.*clang)' | grep -oE '(clang|gcc)' | head -n1
```

e.g. for me

```shell
cc -v 2>&1 | grep -oE '((gcc|clang) version|LLVM version.*clang)' | grep -oE '(clang|gcc)' | head -n1
gcc
```

```shell
clang-5.0 -v 2>&1 | grep -oE '((gcc|clang) version|LLVM version.*clang)' | grep -oE '(clang|gcc)' | head -n1
clang
```

should produce ```clang``` or ```gcc```, but it doesn't for you (even if it should from your output of cc --version (can you try your ```cc``` command both with -v and with --version)?

**Comment by iZsh** [comment]
I managed to compile release 1.3 with the following patch. I couldn't compile the master, even after locally fixing the weak aliases from libhfuzz/memorycmp.c due to some error from netdriver.c

```
libhfnetdriver/netdriver.c:237:49: error: use of undeclared identifier 'MSG_NOSIGNAL'
```

Anyway, here is the patch to apply on r1.3 to make it compile on OS X 10.13 (high sierra):

```
diff --git a/Makefile b/Makefile
index 0d6636f0..780b31cd 100644
--- a/Makefile
+++ b/Makefile
@@ -145,7 +145,7 @@ endif
 
 COMPILER = $(shell $(CC) -v 2>&1 | \
   grep -oE '((gcc|clang) version|LLVM version.*clang)' | \
-  grep -oE '(clang|gcc)' | head -n1)
+  grep --colour=never -oE '(clang|gcc)' | head -n1)
 ifeq ($(COMPILER),clang)
   ARCH_CFLAGS += -Wno-initializer-overrides -Wno-unknown-warning-option
   ARCH_CFLAGS += -fblocks
diff --git a/libhfuzz/instrument.c b/libhfuzz/instrument.c
index 29f2c787..783dbd31 100644
--- a/libhfuzz/instrument.c
+++ b/libhfuzz/instrument.c
@@ -135,14 +135,21 @@ ATTRIBUTE_X86_REQUIRE_SSE42 void __sanitizer_cov_trace_cmp8(uint64_t Arg1, uint6
  * Const versions of trace_cmp, we don't use any special handling for these (for
  * now)
  */
-void __sanitizer_cov_trace_const_cmp1(uint8_t Arg1, uint8_t Arg2)
-    __attribute__((weak, alias("__sanitizer_cov_trace_cmp1")));
-void __sanitizer_cov_trace_const_cmp2(uint16_t Arg1, uint16_t Arg2)
-    __attribute__((weak, alias("__sanitizer_cov_trace_cmp2")));
-void __sanitizer_cov_trace_const_cmp4(uint32_t Arg1, uint32_t Arg2)
-    __attribute__((weak, alias("__sanitizer_cov_trace_cmp4")));
-void __sanitizer_cov_trace_const_cmp8(uint64_t Arg1, uint64_t Arg2)
-    __attribute__((weak, alias("__sanitizer_cov_trace_cmp8")));
+ #if defined(_HF_ARCH_DARWIN)
+ #pragma weak __sanitizer_cov_trace_const_cmp1 = __sanitizer_cov_trace_cmp1
+ #pragma weak __sanitizer_cov_trace_const_cmp2 = __sanitizer_cov_trace_cmp2
+ #pragma weak __sanitizer_cov_trace_const_cmp4 = __sanitizer_cov_trace_cmp4
+ #pragma weak __sanitizer_cov_trace_const_cmp8 = __sanitizer_cov_trace_cmp8
+ #else
+  void __sanitizer_cov_trace_const_cmp1(uint8_t Arg1, uint8_t Arg2)
+     __attribute__((alias("__sanitizer_cov_trace_cmp1")));
+  void __sanitizer_cov_trace_const_cmp2(uint16_t Arg1, uint16_t Arg2)
+     __attribute__((alias("__sanitizer_cov_trace_cmp2")));
+  void __sanitizer_cov_trace_const_cmp4(uint32_t Arg1, uint32_t Arg2)
+     __attribute__((alias("__sanitizer_cov_trace_cmp4")));
+  void __sanitizer_cov_trace_const_cmp8(uint64_t Arg1, uint64_t Arg2)
+     __attribute__((alias("__sanitizer_cov_trace_cmp8")));
+#endif /* defined(_HF_ARCH_DARWIN) */
 
 /*
  * Cases[0] is number of comparison entries
```

**Comment by robertswiecki** [comment]
Thanks for testing! I've presumably solved some of those problems with https://github.com/google/honggfuzz/commit/c44a6efab642d1753320b9acbacdf0de70b9e4a4

**Comment by robertswiecki** [comment]
plus https://github.com/google/honggfuzz/commit/f4cbd8ba63b9962347dac00da56d601b6c88ffe4

**Comment by iZsh** [comment]
Hello again
I pulled the latest version of the master to check your fixes.
A few other fixes are needed, but I managed to compile (not tested yet though) the master branch with the following patch.
NB: I'm not quite sure about the "weak" modification i've made, I'm not familiar with this, hence you might want to review my macro change to make sure this is what you intended)
NB2: you'll also notice a small fix for libhfuzz/persistent.c, the function was returning void from a void function inside a void function.

```
diff --git a/Makefile b/Makefile
index f45cd2d8..287ffa30 100644
--- a/Makefile
+++ b/Makefile
@@ -150,6 +150,8 @@ COMPILER = $(shell $(CC) -v 2>&1 | \
 ifeq ($(COMPILER),clang)
   ARCH_CFLAGS += -Wno-initializer-overrides -Wno-unknown-warning-option
   ARCH_CFLAGS += -fblocks
+  ARCH_CFLAGS += -Wno-gnu-empty-initializer -Wno-format-pedantic
+  ARCH_CFLAGS += -Wno-gnu-statement-expression
   CFLAGS_NOBLOCKS = -fno-blocks
 
   ifneq ($(OS),Darwin)
diff --git a/libhfuzz/memorycmp.c b/libhfuzz/memorycmp.c
index 9a9ef331..2b4e2160 100644
--- a/libhfuzz/memorycmp.c
+++ b/libhfuzz/memorycmp.c
@@ -161,9 +161,16 @@ static inline void* _memmem(const void* haystack, size_t haystacklen, const void
 
 /* Define a weak function x, as well as __wrap_x pointing to x */
 #define XVAL(x) x
+#define STRINGIFY(a) #a
+#if defined(_HF_ARCH_DARWIN)
+#define HF_WEAK_WRAP(ret, func, ...) \
+    _Pragma(STRINGIFY(weak __wrap_##func = func)) \
+    XVAL(ret) XVAL(func)(__VA_ARGS__)
+#else
 #define HF_WEAK_WRAP(ret, func, ...)                                          \
     __attribute__((alias(#func))) XVAL(ret) XVAL(__wrap_##func)(__VA_ARGS__); \
     __attribute__((weak)) XVAL(ret) XVAL(func)(__VA_ARGS__)
+#endif
 
 /* Typical libc wrappers */
 HF_WEAK_WRAP(int, strcmp, const char* s1, const char* s2) {
diff --git a/libhfuzz/persistent.c b/libhfuzz/persistent.c
index e6838d0f..8d8c889c 100644
--- a/libhfuzz/persistent.c
+++ b/libhfuzz/persistent.c
@@ -57,7 +57,7 @@ void HonggfuzzFetchData(const uint8_t** buf_ptr, size_t* len_ptr) {
 }
 
 void HF_ITER(const uint8_t** buf_ptr, size_t* len_ptr) {
-    return HonggfuzzFetchData(buf_ptr, len_ptr);
+    HonggfuzzFetchData(buf_ptr, len_ptr);
 }
 
 static void HonggfuzzRunOneInput(const uint8_t* buf, size_t len) {
```

**Comment by robertswiecki** [comment]
Nice research! Thanks for the diff.

I've applied your changes in https://github.com/google/honggfuzz/commit/89d444ab9038fe79a1a1f757a9e701c2fd887e8f

I've only reverted the direction of weak references. The intention is to have e.g. weak 'strcmp' (so e.g. strcmp from glibc when compiled with -static can override w/o complaints about duplicated symbols) and strong __wrap_strcmp pointing to it. Hope it will work for you.

**Comment by robertswiecki** [comment]
Hi, can we close it, or are there any remaining problems with compiling under MacOSX?

**Comment by teeshop** [comment]
Hi, there is still a problem:
```
libhfnetdriver/netdriver.c:127:26: error: use of undeclared identifier 'SOL_TCP'
    if (setsockopt(sock, SOL_TCP, TCP_NODELAY, &val, (socklen_t)sizeof(val)) == -1) {
```


which I was able to fix using the attached bad hack. (SOL_TCP is not defined)
[macosx_high_sierra.diff.txt](https://github.com/google/honggfuzz/files/1695652/macosx_high_sierra.diff.txt)

**Comment by robertswiecki** [comment]
Thanks, hfnetdriver code fixed in https://github.com/google/honggfuzz/commit/817b596a2418de0ed6ef0af1711608351b320ef3 - is the Makefile patch needed as well?

**Comment by teeshop** [comment]
I needed the Makefile patch because my result of xcrun didn't contain "MacOSX.platform". I don't fully understand the intent of this guard and I don't know if this patch is a good idea, but it works for me.

**Comment by robertswiecki** [comment]
I'd like to release new honggfuzz version, and don't have currently MacOSX platform handy to test it. Would you be able to confirm that honggfuzz compiles under MacOSX, and the basic functionality works (simple fuzzing)?

**Comment by robertswiecki** [comment]
BTW, I also removed this check from the Makefile

**Comment by teeshop** [comment]
The current master builds cleanly on at least my Mac (10.13.2). Unfortunately I cannot simply test basic functionality, because this is my first try using such a tool :-(

**Comment by robertswiecki** [comment]
In absence of physical MacOSX box, I think it's good enough :). Thanks for testing. BTW, version 1.4 has been released - https://github.com/google/honggfuzz/releases

**Comment by robertswiecki** [comment]
Please re-open if there any problems with MacOSX.
